name: Compile PowerShell Scripts

on:
  push:
    branches: [ master ]
    paths: [ 'src/**', 'utils/**', '.github/workflows/compile-scripts.yaml' ]

jobs:
  compile:
    runs-on: windows-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Compile Scripts
      run: ./utils/Invoke-CompileAllScripts.ps1

    - name: Commit Compiled Scripts
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "chore: Compile scripts" -a || echo "No changes to commit"
        git push
