name: Deploy to GitHub Pages

on:
  push:
    branches: [ master ]
    paths: [ 'src/**', 'docs/**', 'utils/Generate-Documentation.ps1', '.github/workflows/deploy-docs.yaml' ]

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  update_docs:
    name: Update documentation
    runs-on: windows-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Generate Documentation
      run: ./utils/Generate-Documentation.ps1

    - name: Commit Compiled Scripts
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "chore: Generate Documentation" -a || echo "No changes to commit"
        git push


  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: update_docs

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false
          standalone: true

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm
          cache-dependency-path: ./docs

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./docs

      - name: Build website
        run: pnpm build
        working-directory: ./docs

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./docs/build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
