name: Lint

on:
  pull_request:
    paths: ["src/**", "tests/**", "utils/**", ".github/workflows/**"]
  push:
    branches: [master]
    paths: ["src/**", "tests/**", "utils/**", ".github/workflows/**"]

jobs:
  powershell:
    name: PowerShell Lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run PSScriptAnalyzer
        uses: microsoft/psscriptanalyzer-action@main
        with:
          path: .\
          recurse: true
          ignorePattern: '"n-sight/cleaners", "compiled/", "external/scripts"'
          settings: .\PSScriptAnalyzerSettings.psd1
          output: results.sarif

      - name: Upload SARIF results
        uses: github/codeql-action/upload-sarif@v3
        if: ${{ always() }}
        with:
          sarif_file: results.sarif
