name: Protect Compiled Directory

on:
  push:
    branches: [ master ]
    paths: [ 'compiled/**', '.github/workflows/protect-compiled-dir.yaml' ]
  pull_request:
    branches: [ master ]
    paths: [ 'compiled/**', '.github/workflows/protect-compiled-dir.yaml' ]

jobs:
  check-modifications:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Check for Changes in 'compiled' Directory
      run: |
        if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'compiled/'; then
          echo "Manual changes to 'compiled' directory are not allowed."
          exit 1
        fi
