name: Scan for Secrets

on: [pull_request, push]

jobs:
  secrets-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install ggshield
      run: pip install ggshield

    - name: Scan Repository
      run: ggshield scan path .
