name: PowerShell Script Tests

on:
  push:
    branches: [master]
    paths: ["src/**", "tests/**", ".github/workflows/test-scripts.yaml"]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Pester Tests
        shell: pwsh
        run: 
