name: Test deployment

on:
  pull_request:
    branches: [ master ]
    paths: [ 'src/**', 'utils/Generate-Documentation.ps1', '.github/workflows/test-deploy.yaml' ]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: CD into docs
        run: cd ./docs

      - uses: pnpm/action-setup@v3
        with:
          version: 8
          dest: ./docs

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm
        #   cache-dependency-path: ./docs/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test build website
        run: pnpm build
